config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'

  resources :products, only: [:index, :show, :new]

  resources :orders, only: [:show, :create, :validate, :update] do
    resources :payments, only: [:new]
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  belongs_to :user
  belongs_to :product
  monetize :amount_cents
end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    order = Order.create!(product: product, product_sku: product.sku, amount_cents: product.price_cents, status_id: 8, user: current_user)
    Stripe.api_key = ENV['STRIPE_SECRET_KEY']


    # link to documentation : https://stripe.com/docs/api/checkout/sessions/create
    session = Stripe::Checkout::Session.create({
      success_url: order_url(order),
      cancel_url: order_url(order),
      line_items:[ quantity: 1,
        price_data:
          {
            currency: 'eur',
            product_data: {name: product.name, description: product.description},
            unit_amount: product.price_cents.to_i
          },
      ],
      mode: 'payment',
      }
    )

    # session = Stripe::Checkout::Session.create({
    #   success_url: order_url(order),
    #   cancel_url: order_url(order),
    #   line_items:[ quantity: 1,
    #     price_data:
    #       {
    #         currency: 'eur',
    #         product: 'prod_MJGZovdFwSQoEs',
    #         unit_amount: 1000
    #       },
    #   ],
    #   mode: 'payment',
    #   }
    # )

    order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def validate
    @order.update(status_id: 9)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(status_id: 8).find(params[:order_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!
  @products = []

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def delete
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/delete.html.erb
<h1>Orders#delete</h1>
<p>Find me in app/views/orders/delete.html.erb</p>

app/views/orders/show.html.erb
<%# <script src="https://js.stripe.com/v3/"></script> %>

<div class="container">
  <div class="col-md-3">
    Le status de la commande n°<%= @order.id %> est "<%= @order.status.name %>"
  </div>
  <div>Montant de la commande : <%= @order.amount %></div>
  <%= @order.checkout_session_id %>
  <div>
   Client : <%= @order.user.email %>
  </div>
  <%= link_to 'Retourner à la homepage', products_path %>
</div>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/orders/validate.html.erb
<h1>Orders#validate</h1>
<p>Find me in app/views/orders/validate.html.erb</p>

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= "image here" %></div>
    <div class="col">
      <h1>Recapitulatif de la commande</h1>
      <p>Purchase of <strong><%= @order.product.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
<button id="pay" class="btn btn-primary">Pay</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @order.checkout_session_id %>'
          });
        });
      </script>
      <%= @order.checkout_session_id %>
    </div>
  </div>
</div>

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/index.html.erb
<script src="https://js.stripe.com/v3/"></script>

<div class= "container">
  <% @products.each do |product| %>
    <ul>
      <h3><%= product.name %></h3>
      <p>Product description : <%= product.description %></p>
      <p>Product stock : <%= product.stock %></p>
      <p>Product price : <%= humanized_money(product.price)%>€</p>
    </ul>
    <%= link_to "More info", product_path(product) %>
  <% end %>
</div>

<div class="addproduct">
  <%= link_to "add a product", new_product_path %>
</div>

app/views/products/new.html.erb
<div class="container">
  <%= simple_form_for @product do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :stock %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/products/show.html.erb
<script src="https://js.stripe.com/v3/"></script>

<ul>
  <li>Name:<%= @product.name %></li>
  <li> Il reste <%= @product.stock %> produits en stock</li>
  <li>Prix : <%=humanized_money(@product.price)%>€</li>
</ul>

<%# <% ER %>
<%# <%=  ==PE %>


<%= form_with url: orders_path, data: {turbo: false} do %>
  <%= hidden_field_tag 'product_id', @product.id %>
  <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
<% end %>